name: Generate and save dependency graph

on:
  pull_request:
    branches: [ "docker-pipeline" ]
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read # 'write' permission is not available

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Generate and save dependency graph
      uses: gradle/actions/dependency-submission@v3
      with:
        dependency-graph: generate-and-upload
