name: Run Gradle Build
on:
  push:
    branches: [ "docker-pipeline" ]
  pull_request:
    branches: [ "docker-pipeline" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          CI=true ./gradlew build --scan
      - name: Check Gradle
        run: |
          ./gradlew dependencyCheckAnalyze --info

  dependency-submission:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        token: ${{ secrets.PAT_TOKEN }} 
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v3
      with: 
         build-scan-publish: true 
         build-scan-terms-of-service-url: "https://gradle.com/terms-of-service" 
         build-scan-terms-of-service-agree: "yes" 
      
  submit-and-review:
      runs-on: ubuntu-latest
      if: github.event_name == 'pull_request'
      needs: build
      steps:
      - name: 'Dependency Review'
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@v3        
