name: Run Gradle Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Set up Gradle Build Action
        uses: gradle/gradle-build-action@v3
        with:
          dependency-graph: generate-and-submit
          cache-disabled: true
          
      - name: Build and test with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build


  submit-and-review:
      runs-on: ubuntu-latest
      if: github.event_name == 'pull_request'
      needs: build
      
      steps:

      - name: 'Dependency Review'
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@v3        
