name: dependency-review

on:
  pull_request:
    branches: [ "docker-pipeline" ]
  # Allows you to run this workflow manually from the Actions tab
  # workflow_run:
  #   workflows: ['name: Download and submit dependency graph']
  #   types: [completed]
permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
    - name: 'Dependency Review'
      uses: actions/dependency-review-action@v3
      with:
        retry-on-snapshot-warnings: true
        retry-on-snapshot-warnings-timeout: 600
